export const TRANSITION_PROGRESS_START  = 0.0000001;
export const TRANSITION_PROGRESS_END    = 0.999;
const OVERLAY_TRANSITION_PROGRESS_START = 0.00000001;
const OVERLAY_TRANSITION_PROGRESS_END   = 0.99999999;

const OVERLAY_INPUT_RANGE = [0, OVERLAY_TRANSITION_PROGRESS_START, 
  OVERLAY_TRANSITION_PROGRESS_END, 1];

const ORIGINAL_INPUT_RANGE = [0, TRANSITION_PROGRESS_START,
  TRANSITION_PROGRESS_END, 1];

export const OVERLAY_VIEWS_VISIBILITY_INPUT_RANGE = OVERLAY_INPUT_RANGE;
export const OVERLAY_VIEWS_VISIBILITY_OUTPUT_RANGE = [0, 1, 1, 0];

export const ORIGINAL_VIEWS_VISIBILITY_INPUT_RANGE = ORIGINAL_INPUT_RANGE;
export const ORIGINAL_VIEWS_VISIBILITY_OUTPUT_RANGE = [1, 0, 0, 1];

